# Generated by Django 3.2.7 on 2021-10-10 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Noutbuk', 'Noutbuk'), ('ultrabuk', 'ultrabuk'), ('Transformer', 'Transformer'), ('Monoblok', 'Monoblok')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=75)),
                ('display_size', models.CharField(choices=[(15.6, 15.6), (14, 14), (13.3, 13.3), (16, 16), (17.2, 17.2)], max_length=40)),
                ('display_type', models.CharField(choices=[('IPS', 'IPS'), ('Oled', 'Oled'), ('TN', 'TN'), ('Tft', 'Tft')], max_length=40)),
                ('CPU', models.CharField(max_length=100)),
                ('RAM', models.CharField(max_length=40)),
                ('Hard', models.CharField(max_length=50)),
                ('courpus', models.CharField(choices=[('Metall', 'Metall'), ('Plastik', 'Plastik'), ('Alyumin', 'Alyumin')], max_length=50)),
                ('colour', models.CharField(max_length=60)),
                ('Batarey', models.CharField(max_length=40)),
                ('Audio', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=60)),
                ('old_price', models.CharField(blank=True, max_length=50, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.brand')),
            ],
        ),
    ]
