# Generated by Django 3.2.7 on 2021-10-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211010_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='display_size',
            field=models.CharField(choices=[('15.6', '15.6'), ('14', '14'), ('13.3', '13.3'), ('16', '16'), ('17.2', '17.2')], max_length=40),
        ),
    ]
